##StaticBody3D variant with support for custom material properties. Automatically generated by LevelBuilder node.
class_name LevelCollider
extends StaticBody3D

##Properties used to differentiate surface materials in collision detection.
@export var material_properties:MaterialProperties
